### ISSUE TITLE
May I ask for your advice! The node red contrib cx alarm log component alarm can only set two alarm conditions

### ISSUE THREAD

**Issue by dangliufeng** [controlx-io/node-red-contrib-cx-alarm-log#1]
1.  May I ask for your advice! The node red contrib cx alarm log component alarm can only set two alarm conditions
<img width="781" alt="屏幕截图 2023-07-03 223417" src="https://github.com/controlx-io/node-red-contrib-cx-alarm-log/assets/92767902/71a49f3f-2276-4e18-bcc9-a7fcef5fd123">
2. As shown in the figure: the result is 3 and the alarm cannot be triggered
![图片](https://github.com/controlx-io/node-red-contrib-cx-alarm-log/assets/92767902/5b9c527d-72d3-4cf8-8327-a828546574ad)

**Comment by dangliufeng** [comment]
<img width="858" alt="屏幕截图 2023-07-03 223513" src="https://github.com/controlx-io/node-red-contrib-cx-alarm-log/assets/92767902/6904ed2e-3d1f-4977-bc01-639533e74385">

**Comment by alex-controlx** [comment]
hm, I never was notified on this issue 😔
anyways just checked the at https://node-red-dev.controlx.io:5010/#!/0
by adding more states to the config
```
Shot Peener,machine_state,,2:Indexing|3:Blasting|4:State 4|5:State 5|6:State 6,
```
And the log shows all 5 states.

It could be an issue with `Channel1.Device1.TT01` value, was it sending value 3 at all?

**Comment by alex-controlx** [comment]
closing it due inactivity
